version: 2.1

orbs:
  cypress: cypress-io/cypress@3.3.1

jobs:
  deploy-to-render-staging:
    docker:
      - image: cimg/base:current
    steps:
      - run:
          name: Deploy to Render Staging
          # TODO: What is happening in the following command?
          # it is sending a POST request to the Render Staging deployhook
          command: |
            echo "Deploying to Render Staging"
            curl $RENDER_STAGING_DEPLOYHOOK

workflows:
  run-tests-and-deploy-to-staging:
    jobs:
      - cypress/run:
          name: run-e2e-tests
          cypress-command: npx cypress run --browser electron --headless
          # Make sure to add MONGODB_URI to ENVIRONMENT VARIABLES in CircleCI so that the tests can connect to the database
          start-command: npm run start:dev
      - cypress/run:
          name: run-component-tests
          cypress-command: npx cypress run --component
      - deploy-to-render-staging:
          # TODO: What does the requires key do?
          # it specifies that the deploy-to-render-staging job requires the run-e2e-tests and run-component-tests jobs to pass before it can run
          requires:
            - run-e2e-tests
            - run-component-tests
          # TODO: What does the filters key do?
          # it specifies that the deploy-to-render-staging job should only run when the branch is main
          filters:
            branches:
              only: main